{% set name = "parsel" %}
{% set version = "1.10.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 14f17db9559f51b43357b9dfe43cec870a8efb5ea4857abb624ec6ff80d8a080

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - cssselect >=1.2.0
    - jmespath
    - lxml
    - packaging
    - w3lib >=1.19.0

test:
  imports:
    - parsel
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/parsel/
  summary: Parsel is a library to extract data from HTML and XML using XPath and CSS selectors
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/scrapy/parsel

extra:
  recipe-maintainers:
    - synapticarbors
    - Gallaecio
    - kmike
    - wRAR
    - dangra
    - rmax
