{% set name = "parsel" %}
{% set version = "1.9.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a5a6bcb0c5fc741540ba3075636ff5cb968852a78cc16ae82250e5d486fa7d48

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - pytest-runner
  run:
    - python >=3.7
    - cssselect >=0.9
    - jmespath
    - lxml
    - packaging
    - w3lib >=1.19.0

test:
  imports:
    - parsel

about:
  home: https://pypi.org/project/parsel/
  summary: Parsel is a library to extract data from HTML and XML using XPath and CSS selectors
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/scrapy/parsel

extra:
  recipe-maintainers:
    - synapticarbors
    - Gallaecio
    - kmike
    - wRAR
    - dangra
    - rmax
